### ISSUE TITLE
How to install the dragnet package?

### ISSUE THREAD

**Issue by AppleSeedExp** [dragnet-org/dragnet#112]
I've got the following error.

Collecting pytest>=4.0.0 (from -r requirements.txt (line 5))
  Using cached pytest-7.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting pytest-cov>=2.6.0 (from -r requirements.txt (line 6))
  Using cached pytest_cov-4.1.0-py3-none-any.whl.metadata (26 kB)
Collecting scikit-learn<0.21.0,>=0.15.2 (from -r requirements.txt (line 7))
  Using cached scikit-learn-0.20.4.tar.gz (11.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "<string>", line 153, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-6v8axpi2\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-6v8axpi2\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-6v8axpi2\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 250, in <module>
        File "<string>", line 238, in setup_package
      ImportError: Numerical Python (NumPy) is not installed.
      scikit-learn requires NumPy >= 1.8.2.
      Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.

**Comment by gi6723** [comment]
I am having the exact same issue and haven't been able to find a solution.

**Comment by sphecter** [comment]
The code seems depricated.

**Comment by robh71** [comment]
This package is way out of date, however it does a good job. If you must use it, consider using it as a service in a container or vm with python 3.7

After many annoying setbacks this is what I am doing and it's used in many projects at my organization.

**Comment by sphecter** [comment]
I found a fork https://github.com/ericluugg/dragnet3.10, I have tried it but seems like the code does not like windows or wsl, maybe I will have to downgrad the full system and use docker to run it, Im looking to update the whole tool to use with the latest version, any idea about the stack ?
